aws:
  cloudFront:
    distribution: null
  s3:
    bucket: null
    bucketPath: null

api:
  baseUrl: http://localhost:7001
  timeout: 1000

puppeteer:
  useRemoteChrome: false
  remoteChromeEndpoint: http://0.0.0.0:9222
  baseUrl: http://0.0.0.0:8080
  slowMoMillis: 0 # Slows puppeteer execution so you can see what is happening. Try 50ms or so.
